[package]
name = "konfiguration"
version = "0.1.0"
rust-version = "1.60"
description = "Json configuration for Rust applications"
homepage = "https://github.com/faveroferreira/konfiguration"
repository = "https://github.com/faveroferreira/konfiguration"
readme = "README.md"
keywords = ["config", "configuration", "settings", "env", "environment"]
authors = ["Guilherme Favero Ferreira <guifaveroferreira@gmail.com>"]
categories = ["config"]
license = "MIT/Apache-2.0"
edition = "2021"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
serde = "1.0"
serde_json = "1.0"
regex = "1.9"
thiserror = "1.0"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }